// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL0Exg2F7y0lTGFQd18BG3mlF4vf8hxOg',
    appId: '1:748350071630:android:8aea353fa11d56b6bc341f',
    messagingSenderId: '748350071630',
    projectId: 'chatapp-10ca2',
    storageBucket: 'chatapp-10ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVDKiblRQAlw_aCcaBBX0DlGAssTip8wo',
    appId: '1:748350071630:ios:ed743538241f3245bc341f',
    messagingSenderId: '748350071630',
    projectId: 'chatapp-10ca2',
    storageBucket: 'chatapp-10ca2.appspot.com',
    androidClientId: '748350071630-fm99h937rc3fs808f1fc134i9sihmcsn.apps.googleusercontent.com',
    iosClientId: '748350071630-q83lrcpkjlepu1ei0sqa9ltll0rle5n6.apps.googleusercontent.com',
    iosBundleId: 'com.lexilearn.lexiLearn',
  );
}
